# Anan's Sketchbook Chat Box Configuration

# 生成图片的热键, 用于 keyboard 库
hotkey: "enter"

# qq头像缓存位置
avatar_cache_location: "./avatar"

# 允许运行此程序的进程列表，只有当前最上层窗口属于这些进程时，热键才会生效
# 例如: ["qq.exe", "weixin.exe"] 表示只在QQ和微信中生效
# 留空列表 [] 表示在所有进程中生效
allowed_processes:
  - "qq.exe"

# 全选快捷键, 此按键并不会监听, 而是会作为模拟输入
select_all_hotkey: "ctrl+a"

# 剪切快捷键, 此按键并不会监听, 而是会作为模拟输入
cut_hotkey: "ctrl+x"

# 黏贴快捷键, 此按键并不会监听, 而是会作为模拟输入
paste_hotkey: "ctrl+v"

# 发送消息快捷键, 此按键并不会监听, 而是会作为模拟输入
send_hotkey: "enter"

# 是否阻塞按键, 如果热键设置为阻塞模式, 则按下热键时不会将该按键传递给前台应用
# 如果生成热键和发送热键相同, 则强制阻塞, 防止误触发发送消息
block_hotkey: false

# 操作的间隔, 如果失效可以适当增大此数值
delay: 0.1

# 生成图片后是否自动发送(模拟回车键输入), 只有开启自动黏贴才生效
auto_send_image: true

# 日志记录等级, 可选值有 "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
logging_level: "INFO"
